echo /usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 -c FstUtils.cc 
/usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 -c FstUtils.cc 

echo /usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 -c mhibm.cc 
/usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 -c mhibm.cc 

echo /usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 -c mhhmm.cc 
/usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 -c mhhmm.cc 

echo /usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 train-mh.cc FstUtils.o mhibm.o mhhmm.o -I/usr/users/chiaying/gcc-4.7/output/include/ -I/usr/users/chiaying/openfst-build/include/ -I/usr/local/include/ -L/usr/users/chiaying/openfst-build/lib/ -L/usr/users/chiaying/gcc-4.7/output/lib64/ -lfst -ldl -pthread -o train-mh 
/usr/users/chiaying/gcc-4.7/output/bin/g++-4.7 -std=c++11 -O3 train-mh.cc FstUtils.o mhibm.o mhhmm.o -I/usr/users/chiaying/gcc-4.7/output/include/ -I/usr/users/chiaying/openfst-build/include/ -I/usr/local/include/ -L/usr/users/chiaying/openfst-build/lib/ -L/usr/users/chiaying/gcc-4.7/output/lib64/ -lfst -ldl -pthread -o train-mh 
